name: Deploy RootSage App

# This workflow runs automatically whenever code is pushed to the 'main' branch.
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    permissions:
      contents: write # Required to push to the gh-pages branch
      pages: write    # Required to deploy to GitHub Pages
      id-token: write # Required for deployment configuration
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 1. Inject API Keys (Firebase and Gemini)
      # This step finds and replaces both API key placeholders with the actual secret values.
      - name: Inject API Keys (Firebase and Gemini)
        run: |
          # Replace $$FIREBASE_API_KEY$$ placeholder
          sed -i "s#\$\$FIREBASE_API_KEY\$\$#${{ secrets.FIREBASE_API_KEY }}#g" index.html
          
          # Replace $$GEMINI_API_KEY$$ placeholder for image analysis
          sed -i "s#\$\$GEMINI_API_KEY\$\$#${{ secrets.GEMINI_API_KEY }}#g" index.html
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }} # <-- NEW: Add Gemini API Key to environment

      # 2. Setup GitHub Pages deployment environment
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # 3. Deploy the modified files to GitHub Pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload the entire repository root directory, which now contains the key-injected index.html
          path: '.'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
